### ISSUE TITLE
No clef sidecar container found after enable clef in swarmSettings and beeConfig

### ISSUE THREAD

**Issue by bitweedx64** [ethersphere/helm#106]

**Comment by renning22** [comment]
```
  ## Enable clef signer
  clef_signer_enable: true
  ## Set clef signer endpoint
  clef_signer_endpoint: "http://localhost:8550"
```

**Comment by EysaDun** [comment]
> ```
>   ## Enable clef signer
>   clef_signer_enable: true
>   ## Set clef signer endpoint
>   clef_signer_endpoint: "http://localhost:8550"
> ```




> ```
>   ## Enable clef signer
>   clef_signer_enable: true
>   ## Set clef signer endpoint
>   clef_signer_endpoint: "http://localhost:8550"
> ```

Are you deploy bzz nodes by k8s?
I got a error for bzz deployment by k8s:
Warning Unhealthy 60m (x448 over 135m) kubelet Readiness probe failed: HTTP probe failed with statuscode: 404
I dont know how to fix it,

**Comment by EysaDun** [comment]
Are you deploy bzz nodes by k8s?
I got a error for bzz deployment by k8s:
Warning Unhealthy 60m (x448 over 135m) kubelet Readiness probe failed: HTTP probe failed with statuscode: 404
I dont know how to fix it,

**Comment by vandot** [comment]
initial issue is resolved, thank @renning22 
closing this
