### ISSUE TITLE
Error: unknown flag: --in-cluster

### ISSUE THREAD

**Issue by flybobdog** [ethersphere/helm#124]
[root@k8s-master ~]# kubectl describe pod beekeeper-pingpong-27053360-2r6t8
Name:         beekeeper-pingpong-27053360-2r6t8
Namespace:    default
Priority:     0
Node:         k8s-node-2/192.168.1.17
Start Time:   Wed, 09 Jun 2021 09:20:41 +0800
Labels:       controller-uid=4ba4ff1f-db5f-4939-b459-a0104dcad55d
              job-name=beekeeper-pingpong-27053360
Annotations:  cni.projectcalico.org/podIP: 
              cni.projectcalico.org/podIPs: 
Status:       Failed
IP:           10.18.140.116
IPs:
  IP:           10.18.140.116
Controlled By:  Job/beekeeper-pingpong-27053360
Containers:
  beekeeper:
    Container ID:  docker://c9ff6254824e80957489943a7994b6cbc3b2d5dae13b76c91adedee7eda456b0
    Image:         ethersphere/beekeeper:latest
    Image ID:      docker-pullable://ethersphere/beekeeper@sha256:613f87d3996bcea9fe1dda78237659d01c41dd38376540a78c5bf86bd4d33776
    Port:          <none>
    Host Port:     <none>
    Args:
      check
      --in-cluster
      pingpong
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 09 Jun 2021 09:20:42 +0800
      Finished:     Wed, 09 Jun 2021 09:20:42 +0800
    Ready:          False
    Restart Count:  0
    Environment:
      BEEKEEPER_API_DOMAIN:              staging.internal
      BEEKEEPER_API_HOSTNAMES:           bee-%d
      BEEKEEPER_API_INSECURE_TLS:        false
      BEEKEEPER_API_SCHEME:              https
      BEEKEEPER_DEBUG_API_DOMAIN:        staging.internal
      BEEKEEPER_DEBUG_API_HOSTNAMES:     bee-%d-debug
      BEEKEEPER_DEBUG_API_INSECURE_TLS:  false
      BEEKEEPER_DEBUG_API_SCHEME:        https
      BEEKEEPER_DISABLE_NAMESPACE:       false
      BEEKEEPER_INSECURE_TLS:            false
      BEEKEEPER_NAMESPACE:               bee
      BEEKEEPER_NODE_COUNT:              1
      BEEKEEPER_PUSH_GATEWAY:            http://localhost:9091/
      BEEKEEPER_PUSH_METRICS:            false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w72nl (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-w72nl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  46m   default-scheduler  Successfully assigned default/beekeeper-pingpong-27053360-2r6t8 to k8s-node-2
  Normal  Pulled     46m   kubelet            Container image "ethersphere/beekeeper:latest" already present on machine
  Normal  Created    46m   kubelet            Created container beekeeper
  Normal  Started    46m   kubelet            Started container beekeeper
-----------------------
the beekeeper can not run for  the arg ' --in-cluster'

**Comment by vandot** [comment]
beekeeper is a internal tool for end to end tests, what are you trying to achive?
