### ISSUE TITLE
Why my pod can not visit SWAP_ENDPOINT?

### ISSUE THREAD

**Issue by EysaDun** [ethersphere/helm#129]
## Enable SWAP
  swap_enable: true
  ## Set swap ethereum blockchain endpoint
  swap_endpoint: wss://goerli.infura.io/ws/v3/mykey-here

it is error after set swap_enable to true and set swap_endpoint.
pods error info:
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  8m47s                   default-scheduler  Successfully assigned default/bzz-helm-release-bee-0 to node02
  Normal   Pulled     8m45s                   kubelet            Container image "ethersphere/clef:0.4.13" already present on machine
  Normal   Created    8m45s                   kubelet            Created container init-clef
  Normal   Started    8m45s                   kubelet            Started container init-clef
  Normal   Pulled     8m41s                   kubelet            Container image "ethersphere/bee:0.5.3" already present on machine
  Normal   Created    8m41s                   kubelet            Created container bee
  Normal   Started    8m41s                   kubelet            Started container bee
  Normal   Pulled     8m41s                   kubelet            Container image "ethersphere/clef:0.4.13" already present on machine
  Normal   Created    8m40s                   kubelet            Created container clef
  Normal   Started    8m40s                   kubelet            Started container clef
  Warning  Unhealthy  3m40s (x27 over 8m20s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 404

notice for last Warning, HTTP 404 err.
i cannot fix this issue.
i was do one my virtual box machine, ubuntu 20.04.
anyone else have the same issue?

**Comment by vandot** [comment]
@EysaDun this issue has nothing to do with helm chart, I am closing it, please check logs of the bee service

**Comment by EysaDun** [comment]
@vandot OK，thanks.
