### ISSUE TITLE
What is the default password of bee image?

### ISSUE THREAD

**Issue by lixiaodong** [ethersphere/helm#130]
When i get in bee node bash.
I can't excute wget command.
I need to know what's the default password of bee image and how to run as root?
![image](https://user-images.githubusercontent.com/1568575/122630644-dbea5880-d0f7-11eb-8bb1-cb8182280f4b.png)

**Comment by EysaDun** [comment]
the same question for me.

**Comment by EysaDun** [comment]
and...  Are you deploy bzz nodes by k8s?

**Comment by EysaDun** [comment]
I got an error by k8s deployment:
 Warning  Unhealthy  60m (x448 over 135m)  kubelet  Readiness probe failed: HTTP probe failed with statuscode: 404
I dont know how to fix it, do you got the error yet?

**Comment by vandot** [comment]
@lixiaodong there is no root password, we implemented have approach as any other project with securityContext https://github.com/ethersphere/helm/blob/master/charts/bee/values.yaml#L32
