### ISSUE TITLE
Missing mainnet config key from bee chart

### ISSUE THREAD

**Issue by bill-95** [ethersphere/helm#138]
Currently getting on bee 1.0.0
`warning msg="no bootnodes defined for network ID1"` due to missing `mainnet` config key.

**Comment by vandot** [comment]
@bill-95 please post config that you used

**Comment by bill-95** [comment]
Dear @vandot Here is the config I'm currently using.
`api-addr: :1633
block-time: 5
bootnode:
bootnode-mode: false
clef-signer-enable: true
clef-signer-endpoint: http://localhost:8550
cors-allowed-origins:
data-dir: /home/bee/.bee
cache-capacity:
db-open-files-limit: 2000
db-block-cache-capacity:
db-write-buffer-size:
db-disable-seeks-compaction:
debug-api-addr: :1635
debug-api-enable: true
full-node: true
gateway-mode:
global-pinning-enable: true
mainnet: true
network-id: 1
password: ********
payment-early:
payment-threshold:
payment-tolerance:
postage-stamp-address:
price-oracle-address:
p2p-addr: :1634
p2p-quic-enable:
p2p-ws-enable:
resolver-options: [https://mainnet.infura.io/v3/********]
standalone:
swap-enable: true
swap-endpoint: ws://**********
swap-factory-address:
swap-legacy-factory-addresses:
swap-deployment-gas-price:
swap-initial-deposit: 0
tracing-enable:
tracing-endpoint:
tracing-service-name:
verbosity: 3
welcome-message: *********
nat-addr: ***********`

**Comment by vandot** [comment]
@bill-95 `bootnode:` is empty, just dont include it
