### ISSUE TITLE
P2P NAT port , init container public IP get timeout.

### ISSUE THREAD

**Issue by frank-netizen** [ethersphere/helm#141]
PUBLIC_IP=$(wget -T 2 http://169.254.169.254/latest/meta-data/public-ipv4 -q -O -);

in POD wget 169.254.169.254,  timeout。 how I get meta-data ？？？

`  - name: init-natport
          image: ethersphere/busybox:1.33
          command:
            - sh
            - -c
            - >
              PUBLIC_IP=$(wget -T 2 http://169.254.169.254/latest/meta-data/public-ipv4 -q -O -);
              export INDEX=$(echo $(hostname) | rev | cut -d'-' -f 1 | rev);
              NAT_PORT=$(( {{ .Values.p2pFixedPort.nodePortStart }} + INDEX ));
              cp -p /tmp/.bee.yaml /home/bee/.bee.yaml;
              printf 'nat-addr: %s:%s\n' "${PUBLIC_IP}" "${NAT_PORT}" >> /home/bee/.bee.yaml;
              echo 'node initialization done';
          volumeMounts:
            - name: config-file
              mountPath: /home/bee
            - name: config
              mountPath: /tmp/.bee.yaml
              subPath: .bee.yaml`

**Comment by frank-netizen** [comment]
PUBLIC_IP=$(wget -T 2 http://169.254.169.254/latest/meta-data/public-ipv4 -q -O -);

is openstack meta api inteface.  if deploy not in openstack will happen error!!!

Suggest： 

env:
            { { - if .Values.publicIp } }
            - name: PUBLIC_IP_ENV
              value: { { .Values.publicIp } }
            { { - end } }
          command:
            - sh
            - -c
            - >
              PUBLIC_IP=${PUBLIC_IP_ENV}
              export INDEX=$(echo $(hostname) | rev | cut -d'-' -f 1 | rev);
              NAT_PORT=$(( {{ .Values.p2pFixedPort.nodePortStart }} + INDEX ));
              cp -p /tmp/.bee.yaml /home/bee/.bee.yaml;
              printf 'nat-addr: %s:%s\n' "${PUBLIC_IP}" "${NAT_PORT}" >> /home/bee/.bee.yaml;
              echo 'node initialization done';

**Comment by bill-95** [comment]
Another solution would be to change 
`PUBLIC_IP=$(wget -T 2 http://169.254.169.254/latest/meta-data/public-ipv4 -q -O -);`
to:
`PUBLIC_IP=$(wget -T 2 icanhazip.com -q -O -);`

**Comment by frank-netizen** [comment]
> Another solution would be to change
> `PUBLIC_IP=$(wget -T 2 http://169.254.169.254/latest/meta-data/public-ipv4 -q -O -);`
> to:
> `PUBLIC_IP=$(wget -T 2 icanhazip.com -q -O -);`

good solve

**Comment by vandot** [comment]
@frank-netizen this endpoint is accepted from multiple platforms and it works
using `icanhazip.com` or any other third party service and leak swarm node IPs is a definite no
if you already know what IP your node is going to have just set it here https://github.com/ethersphere/helm/blob/master/charts/bee/values.yaml#L231
