### ISSUE TITLE
bee chart pinning old version of ethersphere/bee

### ISSUE THREAD

**Issue by mfw78** [ethersphere/helm#77]
**Problem**

The bee helm chart is pinning ethersphere/bee 0.4.2. The current version is 0.5.2. This is causing issues when attempting to deploy a new chequebook by attempting to use an **old** factory. 

**Logs**
![image](https://user-images.githubusercontent.com/53399572/111029894-1f497280-83f7-11eb-91dc-fe0e1cc5bb68.png)

**Fix requested**
Update `values.yaml` in bee chart to use latest ethersphere/bee 0.5.2.

**Comment by vandot** [comment]
Hi @mfw78 thanks for the issue. Bumped to `0.5.3` current release.
