### ISSUE TITLE
bee chart logic for initContainers missing clefSettings.enabled

### ISSUE THREAD

**Issue by mfw78** [ethersphere/helm#78]
**Problem**

When deploying the helm chart with `clefSettings.enabled: true`, the clef initContainer is missing from the resulting Helm template. This causes problems when trying to connect to the clef sidecar container from the bee container.

**Fix requested**
In file `charts/bee/templates/statefulset.yaml`:

```yaml
      {{- end }}
      {{- if or .Values.libp2pSettings.enabled .Values.p2pFixedPort.enabled .Values.swarmSettings.enabled .Values.clefSettings.enabled }}
      initContainers:
        {{- if .Values.libp2pSettings.enabled }}
```

**Comment by vandot** [comment]
Hi @mfw78 thanks for this issues. Yes you are right, this went unnoticed because we at least use `libp2pSettings.enabled` along side `clefSettings.enabled`
