### ISSUE TITLE
bee chart clef container missing required enviroment variable

### ISSUE THREAD

**Issue by mfw78** [ethersphere/helm#79]
**Problem**

When deploying the helm chart, errors are thrown indicating the incorrect chain ID is being used. 

**Logs**
```
time="2021-03-13T10:23:13.303384116Z" level=info msg="using default factory address for chain id 5: f0277caffea72734853b834afc9892461ea18474"
time="2021-03-13T10:23:14Z" level=info msg="no chequebook found, deploying new one."
Error: chequebook init: Invalid chain id.
```

**Fix requsted**
This is caused by the lack of a `CLEF_CHAINID` environment variable in the container definition. Add the following to the container definition:

```yaml
          env:
            - name: CLEF_CHAINID
              value: "5"
```

**Comment by vandot** [comment]
For sure we will expose this at some moment, for now clef running as a side container on k8s is a WIP
