### ISSUE TITLE
bee chart Ingress using deprecated API

### ISSUE THREAD

**Issue by mfw78** [ethersphere/helm#81]
**Problem**
The API being used by the `bee` chart for `Ingress` resources is deprecated.

**Logs**
```
W0313 12:58:03.242389   80230 warnings.go:67] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0313 12:58:03.244980   80230 warnings.go:67] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

**Fix Requested**

- [ ] Update to Ingress API `networking.k8s.io/v1`
- [ ] ~~Update TLS definitions to use one secret to cover all sub-domains, or alternatively, automatically generate the TLS secret names for each ingress / debug ingress~~

**Comment by mfw78** [comment]
Sorry, I modified the issue. It turns out that my `cert-manager` install was messing up (more specifically, it was missing an RBAC role rule that allowed access to the `networking.k8s.io/v1` API Ingress objects (was only looking at deprecated version beforehand).

**Comment by vandot** [comment]
Done https://github.com/ethersphere/helm/pull/101
