### ISSUE TITLE
bee chart LoadBalancer service

### ISSUE THREAD

**Issue by mfw78** [ethersphere/helm#82]
**Problem**

When operating a Kubernetes cluster behind a NAT gateway, it becomes very difficult to port forward to the respective nodes to allow bee to run with maximum accessibility.

**Fix requested**

Configuration to allow each replica to be deployed with a custom P2P port number, or alternatively a port range / base index and iterate up the port for each replica in the StatefulSet. The service should also be adapted to allow per-pod LoadBalancer type services to be deployed, with the ability to specify the IP address range for the LoadBalancerIP.

This would then require custom per-pod bee.yaml or environment variables to allow the NAT port to be specified.

**Comment by vandot** [comment]
Hi @mfw78 thanks for your ticket, this option is already available [p2pFixedPort](https://github.com/ethersphere/helm/blob/master/charts/bee/values.yaml#L52).
This will also set `nat-addr` config option for bee.
If you have any additional questions please reopen this ticket.

**Comment by mfw78** [comment]
Hi @vandot. Thanks for the response. I understand that it is available in `p2pFixedPort`, with `nat-addr`. Using kubernete's Node Ports for the service though creates the issue whereby the pods must consistently be deployed to the same kubernetes worker node, creating an unwanted dependency. 

In the event that a worker node becomes unavailable (perhaps due to underlying system upgrade), it's desirable that the bee pod be gracefully terminated, and started again on another worker node in the Kubernetes cluster. As the node changes, the firewall forwarding rule on NAT would subsequently change, breaking the `nat-addr` that's been advertised to the swarm.

For this reason, if instead the respective services were LoadBalancer types instead (obviously this would require cluster support for `LoadBalancer` type services), this would allow fixed IP addresses to be applied to the respective LoadBalancer services, and migrate gracefully through the cluster, allowing for graceful failover to other worker nodes.
